### ISSUE TITLE
Move server off of Position's AWS account

### ISSUE THREAD

**Issue by emhoracek** [positiondev/mxlinche#17]
There's no hurry, but would like to do this in February some time. 

- [x] Create AWS account -- there may be small charges for storage, etc (I think we outlined these in the proposal) so need somebody's credit card to set it up 
- [x] Copy S3 bucket(s) to new account
- [x] Create EC2 server
- [x] Copy production settings from staging in Trellis
- [x] Backup staging database
- [x] Provision and deploy production WordPress
- [x] Restore database from staging backup
- [x] Switch DNS to production server

**Comment by emhoracek** [comment]
I created the GRAF AWS account with my own personal information for now. Once it's approved, I forward the root login and one of y'all can put your information instead of mine. They want an address, phone number, and credit card on file, FYI. 

I also made an admin cross-account login for Position Dev.

**Comment by alvaroov** [comment]
Any news on when it will be approved?

**Comment by emhoracek** [comment]
The account is approved, but now I'm having other problems. 😞 So I'm going to check in with some friends who know a little more about WordPress than me, see if they have any ideas.

**Comment by emhoracek** [comment]
@alvaroov I tried to start over from scratch, but the problem now doesn't seem to be with WordPress. Instead it's with DNS and the SSL certificates. The DNS issues will probably work themselves out in a few hours, but then I'll still need to figure out the rest of the set-up.

I'm going to continue working on this but I don't believe the site will be ready by tomorrow. I'm sorry about this.

**Comment by emhoracek** [comment]
This is done, finally! Not sure why the DNS took so long to propagate :/
